### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by guilhermej** [joren485/HollowProcess#1]
Hello Joren, can you inform your precise test scenario?
What version of windows? x86 or x64?
What is your payload?

I can't make your script work in Windows 10 and 7 (both x64), but using x86 PE for target and payload.
The near i can get to work is target in svchost in windows 10 with a x86 PE that give me the 0xC0000005 error. In the other scenarios the script can create a suspended process but triggers an error in get_context().

Can you help me?

**Comment by joren485** [comment]
Hi,

What most likely happened, is that some recent changes in [`pefile`](https://github.com/erocarrera/pefile) changed the type of objects used in this code. Unfortunately, I do not have enough time at the moment to rewrite the code. 

If you want to learn more about this technique I suggest you read [this code](http://www.rohitab.com/discuss/topic/40262-dynamic-forking-process-hollowing/).

**Comment by guilhermej** [comment]
Thanks, I will read about and try to fix the code and make a pull request if I can get this to work.

**Comment by Marshall13** [comment]
I also encounter the same error.
Even after installing an old version of Pefile from 2014 (= https://github.com/erocarrera/pefile/tree/8b9bbc7f8883f69ad9ecdce44ff17d7ecd74997a) or 2015, I also meet her ...
So I do not think this hypothesis can be right ... And I do not know where to turn to solve this problem ...
Did you have another hypothesis to guide me to fix this error?
thank you very much in advance

**Comment by joren485** [comment]
I found some time to look into this. I updated and fixed the code.
