### ISSUE TITLE
Hollow svhost Process

### ISSUE THREAD

**Issue by Nile2020** [joren485/HollowProcess#2]
Hi there, 
I have a problem with one of a "svhost processes service" that consumes my cpu sources especially If when I went online.

Mcafee has discovered some melodious files and fixed them After a full scan but the problem remains.

Also There 's Something weird happened, When I am trying to shut down the Laptop, a blue screen appears saying I need to restart to fix errors Critical_ Process_Died.

I made a scan with Zemana Anti-Maleware and it found that two files in the picture blow but when trying to repair it, it did nothing and the problem came again.

![hollow process](https://user-images.githubusercontent.com/26345889/37180725-bbf336a8-2332-11e8-81b3-90329c58f526.jpg)

Also Glasswire shows this alarm from time to time saying "You connect to a suspicious host".

![hollow process 02](https://user-images.githubusercontent.com/26345889/37180803-0e23fc00-2333-11e8-940b-fa4566e309b7.jpg)

How to fix that ?
Thank you.

Mahmoud

**Comment by joren485** [comment]
This is issue does not seem related to this repo.
